// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// PrometheeI
List PrometheeI(Eigen::MatrixXd datMat, Eigen::VectorXd vecWeights, Eigen::VectorXi prefFunction, Eigen::MatrixXd parms, bool normalize);
RcppExport SEXP RMCriteria_PrometheeI(SEXP datMatSEXP, SEXP vecWeightsSEXP, SEXP prefFunctionSEXP, SEXP parmsSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type datMat(datMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type vecWeights(vecWeightsSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type prefFunction(prefFunctionSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type parms(parmsSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(PrometheeI(datMat, vecWeights, prefFunction, parms, normalize));
    return rcpp_result_gen;
END_RCPP
}
// PrometheeII
Eigen::VectorXd PrometheeII(Eigen::MatrixXd datMat, Eigen::VectorXd vecWeights, Eigen::VectorXi prefFunction, Eigen::MatrixXd parms, bool normalize);
RcppExport SEXP RMCriteria_PrometheeII(SEXP datMatSEXP, SEXP vecWeightsSEXP, SEXP prefFunctionSEXP, SEXP parmsSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type datMat(datMatSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type vecWeights(vecWeightsSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type prefFunction(prefFunctionSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type parms(parmsSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(PrometheeII(datMat, vecWeights, prefFunction, parms, normalize));
    return rcpp_result_gen;
END_RCPP
}
