# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PrometheeI <- function(datMat, vecWeights, prefFunction, parms, normalize) {
    .Call('RMCriteria_PrometheeI', PACKAGE = 'RMCriteria', datMat, vecWeights, prefFunction, parms, normalize)
}

PrometheeII <- function(datMat, vecWeights, prefFunction, parms, normalize) {
    .Call('RMCriteria_PrometheeII', PACKAGE = 'RMCriteria', datMat, vecWeights, prefFunction, parms, normalize)
}

