# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create the Kernel matrix
#' @param datVec  Column of the dataset
#' @param int Type od preference function
#' @return Preference Matrix
NULL

#' Create the Kernel matrix
#' @param datVec  Column of the dataset
#' @param int Type od preference function
#' @return Preference Matrix
PrometheeI <- function(datMat, vecWeights, prefFunction, parms, normalize) {
    .Call('_RMCriteria_PrometheeI', PACKAGE = 'RMCriteria', datMat, vecWeights, prefFunction, parms, normalize)
}

#' Create the Kernel matrix
#' @param datVec  Column of the dataset
#' @param int Type od preference function
#' @return Preference Matrix
NULL

#' Create the Kernel matrix
#' @param datVec  Column of the dataset
#' @param int Type od preference function
#' @return Preference Matrix
#'' [[Rcpp::export]]
NULL

#' Create the Kernel matrix
#' @param datVec  Column of the dataset
#' @param int Type od preference function
#' @return Preference Matrix
NULL

#' Create the Kernel matrix
#' @param datVec  Column of the dataset
#' @param int Type od preference function
#' @return Preference Matrix
PrometheeIII <- function(datMat, vecWeights, prefFunction, alphaVector, parms) {
    .Call('_RMCriteria_PrometheeIII', PACKAGE = 'RMCriteria', datMat, vecWeights, prefFunction, alphaVector, parms)
}

#' Create the Kernel matrix
#' @param datVec  Column of the dataset
#' @param int Type od preference function
#' @return Preference Matrix
PrometheeIV <- function(datMat, vecWeights, prefFunction, parms, normalize) {
    .Call('_RMCriteria_PrometheeIV', PACKAGE = 'RMCriteria', datMat, vecWeights, prefFunction, parms, normalize)
}

#' Create the Kernel matrix
#' @param datVec  Column of the dataset
#' @param int Type od preference function
#' @return Preference Matrix
PrometheeIVKernel <- function(datMat, vecWeights, prefFunction, parms, band, normalize) {
    .Call('_RMCriteria_PrometheeIVKernel', PACKAGE = 'RMCriteria', datMat, vecWeights, prefFunction, parms, band, normalize)
}

